version: "2"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - "GF_INSTALL_PLUGINS=grafana-clock-panel"

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports: 
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment: 
      - "INFLUXDB_DATA_INDEX_VERSION=tsil"